import { WindowConfig } from './WindowConfig';

export const AuraWindowConfig: WindowConfig = {
  baseSettings: {
    width: 420,
    height: 420,
    alwaysOnTop: true,
    show: true,
    fullscreenable: false,
    focusable: true,
    enableLargerThanScreen: true,
    frame: false,
    hasShadow: false,
    transparent: true,
    skipTaskbar: true,
    titleBarStyle: 'hidden',
    backgroundColor: '#00000000',
    type: 'panel',
    paintWhenInitiallyHidden: true,
    movable: true,
    resizable: true,
    minWidth: 320,
    minHeight: 200,
  },
  behavior: {
    showBehavior: {
      opacity: 1,
      ignoreMouseEvents: false,
      skipTaskbar: true,
      alwaysOnTop: true,
      alwaysOnTopLevel: 'screen-saver',
      visibleOnAllWorkspaces: true,
      visibleOnFullScreen: true,
      focusable: true,
      contentProtection: false,
    },
    hideBehavior: {
      opacity: 0,
      ignoreMouseEvents: true,
      skipTaskbar: true,
      alwaysOnTop: true,
      alwaysOnTopLevel: 'screen-saver',
      visibleOnAllWorkspaces: true,
      visibleOnFullScreen: true,
      focusable: false,
      contentProtection: false,
    },
    platformSpecific: {
      darwin: {
        hiddenInMissionControl: true,
        windowButtonVisibility: false,
        backgroundColor: '#00000000',
        hasShadow: false,
      },
      win32: {
        thickFrame: false,
      },
    },
  },
};
